version: '3.8'

services:
  web:
    build: .
    entrypoint: /usr/src/app/entrypoint.sh
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery:
    build: .
    entrypoint: /usr/src/app/celery-entrypoint.sh
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: "redis:alpine"

volumes:
  postgres_data: