from pydantic import BaseModel, Field
from typing import List

class GuidelineSummary(BaseModel):
    """
    Pydantic model to validate the structure of the summary
    generated by the OpenAI API.
    """
    summary: str

class ChecklistItem(BaseModel):
    """
    Pydantic model for a single item in the generated checklist.
    """
    task: str
    is_complete: bool = False

class Checklist(BaseModel):
    """
    Pydantic model to validate the overall structure of the checklist
    generated by the OpenAI API.
    """
    items: List[ChecklistItem]